name: 'Raw Upload'
description: 'Upload raw images and files and get a URL.'
branding:
  icon: 'image'
  color: 'green'
inputs:
  path:
    description: 'File path Ex: images/image.png'
    required: true
  branch:
    description: 'Branch name'
    required: false
    default: 'images'
outputs:
  url:
    description: "https://raw.githubusercontent.com/user/repo/refs/heads/branch/image.png"
    value: ${{ steps.raw.outputs.url }}
runs:
  using: "composite"
  steps:
    - uses: stefanzweifel/git-auto-commit-action@v7
      with:
        branch: ${{ inputs.branch }}
        create_branch: true
        file_pattern: output.png
        skip_checkout: true
        commit_options: '--no-verify'
        push_options: '--force'

    - name: Get Raw URL
      id: raw
      run: echo "url=https://raw.githubusercontent.com/$REPO/refs/heads/$INPUT_BRANCH/$INPUT_PATH" >> $GITHUB_OUTPUT
      shell: bash
      env:
        REPO: ${{ github.repository }}
        INPUT_PATH: ${{ inputs.path }}
        INPUT_BRANCH: ${{ inputs.branch }}